name: Minecord
version: '${project.version}'
main: de.epsdev.minecord.Minecord
api-version: 1.18
authors: [ EliasSchramm ]
description: Connects your server chat with a discord channel.
website: https://gitlab.eps-dev.de/Elias/minecrod.git
commands:
  clearDiscordBotCache:
    description: Clears the Discord bot cache. Intended to be used in case of some odd desyncs.
    usage: /<command>
    permission: minecord.clearDiscordBotCache